// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SearchTerms       []string               `protobuf:"bytes,1,rep,name=searchTerms,proto3" json:"searchTerms,omitempty"`
	TitleExclusions   []string               `protobuf:"bytes,2,rep,name=title_exclusions,json=titleExclusions,proto3" json:"title_exclusions,omitempty"`
	ExcludeNullPay    bool                   `protobuf:"varint,3,opt,name=excludeNullPay,proto3" json:"excludeNullPay,omitempty"`
	PayMin            uint32                 `protobuf:"varint,4,opt,name=payMin,proto3" json:"payMin,omitempty"`
	CompanyExclusions []string               `protobuf:"bytes,5,rep,name=company_exclusions,json=companyExclusions,proto3" json:"company_exclusions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetSearchTerms() []string {
	if x != nil {
		return x.SearchTerms
	}
	return nil
}

func (x *SearchRequest) GetTitleExclusions() []string {
	if x != nil {
		return x.TitleExclusions
	}
	return nil
}

func (x *SearchRequest) GetExcludeNullPay() bool {
	if x != nil {
		return x.ExcludeNullPay
	}
	return false
}

func (x *SearchRequest) GetPayMin() uint32 {
	if x != nil {
		return x.PayMin
	}
	return 0
}

func (x *SearchRequest) GetCompanyExclusions() []string {
	if x != nil {
		return x.CompanyExclusions
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobResult           `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetJobs() []*JobResult {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Company       string                 `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	PayMin        *float64               `protobuf:"fixed64,3,opt,name=pay_min,json=payMin,proto3,oneof" json:"pay_min,omitempty"`
	PayMax        *float64               `protobuf:"fixed64,4,opt,name=pay_max,json=payMax,proto3,oneof" json:"pay_max,omitempty"`
	PayType       string                 `protobuf:"bytes,5,opt,name=pay_type,json=payType,proto3" json:"pay_type,omitempty"`
	DupCount      int32                  `protobuf:"varint,6,opt,name=dup_count,json=dupCount,proto3" json:"dup_count,omitempty"`
	MaxApplicants *int32                 `protobuf:"varint,7,opt,name=max_applicants,json=maxApplicants,proto3,oneof" json:"max_applicants,omitempty"`
	MinApplicants *int32                 `protobuf:"varint,8,opt,name=min_applicants,json=minApplicants,proto3,oneof" json:"min_applicants,omitempty"`
	FirstSeen     string                 `protobuf:"bytes,9,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen      string                 `protobuf:"bytes,10,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ApplyUrls     []string               `protobuf:"bytes,11,rep,name=apply_urls,json=applyUrls,proto3" json:"apply_urls,omitempty"`
	PostedDate    string                 `protobuf:"bytes,12,opt,name=posted_date,json=postedDate,proto3" json:"posted_date,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *JobResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *JobResult) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *JobResult) GetPayMin() float64 {
	if x != nil && x.PayMin != nil {
		return *x.PayMin
	}
	return 0
}

func (x *JobResult) GetPayMax() float64 {
	if x != nil && x.PayMax != nil {
		return *x.PayMax
	}
	return 0
}

func (x *JobResult) GetPayType() string {
	if x != nil {
		return x.PayType
	}
	return ""
}

func (x *JobResult) GetDupCount() int32 {
	if x != nil {
		return x.DupCount
	}
	return 0
}

func (x *JobResult) GetMaxApplicants() int32 {
	if x != nil && x.MaxApplicants != nil {
		return *x.MaxApplicants
	}
	return 0
}

func (x *JobResult) GetMinApplicants() int32 {
	if x != nil && x.MinApplicants != nil {
		return *x.MinApplicants
	}
	return 0
}

func (x *JobResult) GetFirstSeen() string {
	if x != nil {
		return x.FirstSeen
	}
	return ""
}

func (x *JobResult) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *JobResult) GetApplyUrls() []string {
	if x != nil {
		return x.ApplyUrls
	}
	return nil
}

func (x *JobResult) GetPostedDate() string {
	if x != nil {
		return x.PostedDate
	}
	return ""
}

func (x *JobResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\"\xcb\x01\n" +
	"\rSearchRequest\x12 \n" +
	"\vsearchTerms\x18\x01 \x03(\tR\vsearchTerms\x12)\n" +
	"\x10title_exclusions\x18\x02 \x03(\tR\x0ftitleExclusions\x12&\n" +
	"\x0eexcludeNullPay\x18\x03 \x01(\bR\x0eexcludeNullPay\x12\x16\n" +
	"\x06payMin\x18\x04 \x01(\rR\x06payMin\x12-\n" +
	"\x12company_exclusions\x18\x05 \x03(\tR\x11companyExclusions\"7\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x04jobs\x18\x01 \x03(\v2\x11.search.JobResultR\x04jobs\"\xe3\x03\n" +
	"\tJobResult\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acompany\x18\x02 \x01(\tR\acompany\x12\x1c\n" +
	"\apay_min\x18\x03 \x01(\x01H\x00R\x06payMin\x88\x01\x01\x12\x1c\n" +
	"\apay_max\x18\x04 \x01(\x01H\x01R\x06payMax\x88\x01\x01\x12\x19\n" +
	"\bpay_type\x18\x05 \x01(\tR\apayType\x12\x1b\n" +
	"\tdup_count\x18\x06 \x01(\x05R\bdupCount\x12*\n" +
	"\x0emax_applicants\x18\a \x01(\x05H\x02R\rmaxApplicants\x88\x01\x01\x12*\n" +
	"\x0emin_applicants\x18\b \x01(\x05H\x03R\rminApplicants\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"first_seen\x18\t \x01(\tR\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\n" +
	" \x01(\tR\blastSeen\x12\x1d\n" +
	"\n" +
	"apply_urls\x18\v \x03(\tR\tapplyUrls\x12\x1f\n" +
	"\vposted_date\x18\f \x01(\tR\n" +
	"postedDate\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescriptionB\n" +
	"\n" +
	"\b_pay_minB\n" +
	"\n" +
	"\b_pay_maxB\x11\n" +
	"\x0f_max_applicantsB\x11\n" +
	"\x0f_min_applicants2D\n" +
	"\tJobSearch\x127\n" +
	"\x06Search\x12\x15.search.SearchRequest\x1a\x16.search.SearchResponseB\x0eZ\fsearch/protob\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: search.SearchRequest
	(*SearchResponse)(nil), // 1: search.SearchResponse
	(*JobResult)(nil),      // 2: search.JobResult
}
var file_proto_search_proto_depIdxs = []int32{
	2, // 0: search.SearchResponse.jobs:type_name -> search.JobResult
	0, // 1: search.JobSearch.Search:input_type -> search.SearchRequest
	1, // 2: search.JobSearch.Search:output_type -> search.SearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	file_proto_search_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
