// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/search.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobSearch_Search_FullMethodName = "/search.JobSearch/Search"
)

// JobSearchClient is the client API for JobSearch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobSearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type jobSearchClient struct {
	cc grpc.ClientConnInterface
}

func NewJobSearchClient(cc grpc.ClientConnInterface) JobSearchClient {
	return &jobSearchClient{cc}
}

func (c *jobSearchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, JobSearch_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobSearchServer is the server API for JobSearch service.
// All implementations must embed UnimplementedJobSearchServer
// for forward compatibility.
type JobSearchServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	mustEmbedUnimplementedJobSearchServer()
}

// UnimplementedJobSearchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobSearchServer struct{}

func (UnimplementedJobSearchServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedJobSearchServer) mustEmbedUnimplementedJobSearchServer() {}
func (UnimplementedJobSearchServer) testEmbeddedByValue()                   {}

// UnsafeJobSearchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobSearchServer will
// result in compilation errors.
type UnsafeJobSearchServer interface {
	mustEmbedUnimplementedJobSearchServer()
}

func RegisterJobSearchServer(s grpc.ServiceRegistrar, srv JobSearchServer) {
	// If the following call panics, it indicates UnimplementedJobSearchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobSearch_ServiceDesc, srv)
}

func _JobSearch_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobSearchServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobSearch_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobSearchServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JobSearch_ServiceDesc is the grpc.ServiceDesc for JobSearch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobSearch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.JobSearch",
	HandlerType: (*JobSearchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _JobSearch_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/search.proto",
}
